apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres-deploy
  name: postgres-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: postgres-deploy
    spec:
      containers:
      - image: postgres
        name: postgres-deploy
        volumeMounts:
        - mountPath: "/data"
          name: postgres-vol
      volumes:
      - name: postgres-vol
        persistentVolumeClaim:
          claimName: my-pv-claim
      restartPolicy: Always
