apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvvol-1
spec:
   capacity:
      storage: 1Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      path: /
      server: 10.100.162.13
      readOnly: false
