apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
   name: restricted
spec:
   seLinux:
      rule: RunAsAny
   supplementalGroups:
      rule: RunAsAny
   runAsUser:
      rule: MustRunAsNonRoot
   fsGroup:
      rule: RunAsAny
